### ISSUE TITLE
[Feature Request] Ability to Display File/Image Information

### ISSUE THREAD

**Issue by luxlogica** [sylvainjule/kirby-previews#3]
Kirby's default for listing image entries in a structure field table is to simply show a tiny little square preview of the image. Often, that is not sufficient, and we need more information - eg.: the file name, the file dimensions, the file size, etc.

It would be wonderful if Kirby Previews could enable the user to **optionally** display added file information in these entries - perhaps via config options. Example:

``` php
<?php 

return [
    // toggle thumbnail previews for images
    'sylvainjule.kirbypreviews.filethumb' => false,

    // extra information to display for file/image fields
    'sylvainjule.kirbypreviews.fileinfo' => "{{ file.filename }}"
];
```

**Comment by sylvainjule** [comment]
I have drafted a preview but couldn't figure out how to pass props to preview components. 
So, this isn't a conditional option and will require a bit of manual actions.

1. Follow the 3 first steps [here](https://github.com/sylvainjule/kirby-previews#3-add--edit-a-preview)
2. Uncomment:
    - Line 2 and 15 [here](https://github.com/sylvainjule/kirby-previews/blob/master/src/index.js#L2)
    - [This](https://github.com/sylvainjule/kirby-previews/blob/f14619596642452f02b85758db27240865fa3d2e/src/assets/css/styles.scss#L99-L123)
3. Run `npm run build`
