### ISSUE TITLE
[Feature Request] Support for the new `blocks` field type

### ISSUE THREAD

**Issue by raphaelsaunier** [sylvainjule/kirby-previews#5]
It would be great to add support for the new `blocks` field type introduced in Kirby `3.5.0`. 

Currently, the previews are hardly useful:

![image](https://user-images.githubusercontent.com/170256/105189462-47260380-5b35-11eb-95b3-1a7df9b8f163.png)

Happy to submit a PR if you agree that this is in the scope of this plugin!

**Comment by sylvainjule** [comment]
This is definitely in the scope of this plugin, as I haven't had a lot of usage for the new blocks field yet a PR would be awesome!
